### ISSUE TITLE
Is there a reason why we have the ability to pause/play the video?

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Mayday-Web#14]

**Comment by gireeshspan** [comment]
There is no specific reason and it is default feature of HTML5 video element.

By using this user want to pause the remote video and resume.

**Comment by atsakiridis** [comment]
@gireeshspan I think that this ends up confusing the user a lot. But since Despina is already working on mockups, let's continue this discussion in that context. Closing this
