### ISSUE TITLE
I couldn't get annotations to work

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Mayday-Web#15]
Both for Chrome and Firefox. The document is shared but when the Agent clicks and drags with the cross cursor nothing is shown in the customer side. 

Is there anything else I should do for that to work?

**Comment by gireeshspan** [comment]
Annotation feature not supported for PDF file share, as of now annotation supported only in screen share/co browsing.

**Comment by atsakiridis** [comment]
Ok understood @gireeshspan, closing this. Thanks
